version: "3.8"
services:
  RabbitMQ_Standalone:
   image: rabbitmq:management-alpine
   container_name: 'RabbitMQ_Standalone'
   restart: unless-stopped
   volumes:
    - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
    - ./definitions.json:/etc/rabbitmq/definitions.json:ro
   ports:
    - 5672:5672 # AMQP protocol port
    - 15672:15672 # HTTP management UI
   logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1" 